framework:
<<<<<<< HEAD
<<<<<<< HEAD
    mailer:
        dsn: '%env(MAILER_DSN)%'
=======
  mailer:
    dsn: "%env(MAILER_DSN)%"
    message_bus: false
>>>>>>> origin/gestionuser
=======
    mailer:
        dsn: '%env(MAILER_DSN)%'
>>>>>>> origin/gestionpost
