security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  role_hierarchy:
    ROLE_ADMIN: []
    ROLE_AGRICULTURE: []
    ROLE_RECYCLING_INVESTOR: []
    ROLE_RESOURCE_INVESTOR: []
    ROLE_USER:
      [ROLE_AGRICULTURE, ROLE_RECYCLING_INVESTOR, ROLE_RESOURCE_INVESTOR]

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Controller\GestionUser\AppAuthenticator
      logout:
        path: app_logout
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 86400
        always_remember_me: false

  access_control: # <-- Correct indentation ici !
    - { path: ^/api/users, roles: PUBLIC_ACCESS }
    - { path: ^/matched-users, roles: PUBLIC_ACCESS }
    - { path: ^/dashboard, roles: ROLE_ADMIN }

    
