controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
update_event_places:
    path: /update-event-places/{id}
    controller: App\Controller\EventController::updatePlaces
    methods: [POST]
