parameters:
  images_directory: "%kernel.project_dir%/public/uploads/images"
  rapid_api_key: "%env(RAPID_API_KEY)%"
  infobip_api_url: '%env(INFOBIP_API_URL)%'
  infobip_api_key: '%env(INFOBIP_API_KEY)%'
  infobip_sender: '%env(INFOBIP_SENDER)%'
  rapid_api_key_translation: '%env(RAPID_API_KEY_TRANSLATION)%'
  translation_api_url: '%env(TRANSLATION_API_URL)%'
  translation_api_host: '%env(TRANSLATION_API_HOST)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Importation automatique de tous les services du répertoire src/
  # On exclut uniquement les dossiers ou fichiers non concernés
  App\:
    resource: '../src/'
    exclude:
      - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
      - '../src/Service/InfobipSmsSender.php'  # Pour éviter le conflit d'auto-discovery

  App\Service\NotificationService: ~

  App\Service\InfobipSmsSender:
    arguments:
      $client: '@http_client'
      $apiUrl: '%env(INFOBIP_API_URL)%'
      $apiKey: '%env(INFOBIP_API_KEY)%'
      $sender: '%env(INFOBIP_SENDER)%'

  App\Service\PredictService:
        arguments:
            $client: '@http_client'


  App\Service\TranslationService:
    arguments:
      $apiUrl: '%translation_api_url%'
      $apiKey: '%rapid_api_key_translation%'
      $apiHost: '%translation_api_host%'



  App\Controller\GestionReclamation\ReponsesController:
    arguments:
      $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
      $rapidApiKey: '%env(RAPID_API_KEY)%'

  App\Controller\GestionReclamation\PlanteController:
    arguments:
      $client: '@Symfony\Contracts\HttpClient\HttpClientInterface'
      $rapidApiKey: '%env(RAPID_API_KEY)%'
